<ManagerScreens@ScreenManager>:
    StartScreen:
        id: start_screen
    MenuScreen:
        id: men
    StuChoiceScreen:
        id: stu_cho_screen
    SldChoiceScreen:
        id: sld_cho_screen

<StartScreen@Screen>
    name: "start_screen"

    FloatLayout:
        Button:
            text: "Продолжить"
            on_press: app.screen_manager.current = 'menu'
            pos: (650/2-100, 20)
            size: 200, 100
            size_hint: None, None
    Label:
        text: "Добро пожаловать в программу, которая поможет Вам в выборе страны для отдыха"
        color: [.45, .64, .84, 1]
        size_hint_y: None
        height: self.texture_size[1]
        width: self.texture_size[1]
        text_size: self.width, None
        pos: (25, 500)

        font_size: 30



<MenuScreen@Screen>:
    name: "menu"

    BoxLayout:
        orientation: 'vertical'
        Button:
            text: "Студент"
            on_press: app.screen_manager.current = 'stu_cho_screen'
        Button:
            text: "Служащий"
            on_press: app.screen_manager.current = 'sld_cho_screen'

<StuChoiceScreen@Screen>
    name: "stu_cho_screen"

    BoxLayout:
        orientation: 'vertical'
        Button:
            text: "Теплая страна"

        Button:
            text: "Холодная страна"

<SldChoiceScreen@Screen>
    name: "sld_cho_screen"

    BoxLayout:
        orientation: 'vertical'
        Button:
            text: "Теплая страна"

        Button:
            text: "Холодная страна"
